# SwiftLint Configuration for Vibe Screenshoter

# Paths to include during linting
included:
  - Sources

# Paths to ignore during linting
excluded:
  - .build
  - Tests
  - .swiftpm

# Disable rules
disabled_rules:
  - trailing_whitespace
  - todo

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_imports

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y

# Number of leading whitespace characters
indentation: 4

# Enforce explicit type annotations for properties
explicit_type_interface:
  excluded:
    - local

# Custom rules
custom_rules:
  no_print:
    name: "Avoid Print Statements"
    regex: "print\\("
    message: "Use proper logging instead of print()"
    severity: warning
